<iframe src="<?php echo $block->getLmmapUrl(); ?>" style="position: absolute;top: 0;bottom: 0;left: 0;right: 0;height: 100%;width: 100%;border: 0;"></iframe>
<script type="text/javascript">
    /*<![CDATA[*/
    function listenMessage(msg) {
        var point = JSON.parse(msg.data);
        window.opener.document.getElementById('parcelshop_sap').value=point.sap;
        window.opener.document.getElementById('parcelshop_zip').value=point.zip;
        window.opener.document.getElementById('parcelshop_city').value=point.city;
        var name = point.name + ', ' + point.street + ' ' + point.streetNo;
        if (point.houseNo != '') {
            name += '/'+ point.houseNo;
        }
        name += ', ' + point.zip + ' ' + point.city;
        window.opener.document.getElementById('parceslhop_desc').innerHTML=name;



        self.close();
    }
    if (window.addEventListener) {
        window.addEventListener("message", listenMessage, false);
    } else {
        window.attachEvent("onmessage", listenMessage);
    }
    /*]]>*/
</script>
